### ISSUE TITLE
Maybe rename "Vertex" into "Corner"

### ISSUE THREAD

**Issue by eliemichel** [eliemichel/OpenMfx#12]
The terms point/vertex/face were originally chosen according to [Houdini's naming convention](https://www.sidefx.com/docs/hengine/_h_a_p_i__attributes.html), and it also matches [Pixar's USD](https://graphics.pixar.com/usd/docs/api/class_usd_geom_mesh.html). But "vertex" is misleading to many people because in some softwares it may have a different meaning. In particular, in Blender, Maya and 3DS Max it means what we call "point", making everything a bit harder to follow.

A good candidate so far seems to be **"Corner"**, as in "face corner", which already feels like the most natural way to explain what "vertices" are with respect to "points". Other existing names are **"Loops"** (quite unique to Blender, and a bit ill-named imho even though I understand why it is so) or **"Elements"** (as in "element buffer" using in graphic APIs, I find it more abstract).

Memo of things to change in case of such a renaming (it'll touch a lot of things):

 - [x] Rename in all ofxMeshEffect.h
 - [x] Rename in API reference
 - [x] Rename in C++ SDK
 - [x] Rename in SDK tutorial and figures
 - [x] Rename variables in host implementation

External input and thoughs are welcome here!

(Thanks @tkarabela for [investingating about other APIs](https://github.com/eliemichel/OpenMeshEffect/issues/6#issuecomment-715966550) btw)

**Comment by tkarabela** [comment]
(First, let me say that the C++ tutorial is great! :)

To help people better understand the representation, I wouldn't hesitate to put the figure describing attributes from the [C++ tutorial](https://openmesheffect.org/Guide/TutorialCppSdk.html) also into the C API reference, where `OfxMeshHandle` etc. are discussed ( https://openmesheffect.org/Reference/ofxMeshEffectAPI.html ). Perhaps there could be another figure showing how common types of geometry are represented (point cloud, edge wireframe, polygonal mesh), which could also illustrate how `NoLooseEdge` and `ConstantFaceCount` are used. Like they say, a picture is worth a thousand words :) When learning about how geometry in Houdini works, the diagram in https://www.sidefx.com/docs/houdini/model/attributes.html#geometry-components was very informative.

The impression I got from looking at the various SDKs was that they are all slightly different, so you still have to look at the schema to see what they actually mean, and point/vertex/face/mesh seem good to me. I don't have experience with Maya/3DS, but Blender (as far as UI goes) is confused: there are "vertex groups/weights" (OFX point attributes), but also "vertex colors / vertex painting" (which are actually "loop colors", or OFX vertex attributes). In the "Data Transfer" modifier, there are "Vertex Data" and "Face Corner Data" sections, where "vertex groups" and "vertex colors" live, respectively.

**"Elements"** sounds confusing to me, I'm not sure if it refers to faces or face-corners. **"Corners"** is fine (vertex/corner/face/mesh). I still like **"Vertex"** (point/vertex/face/mesh) best, the other options don't seem like a clear win to me.

---

On the topic of naming, one thing that might be a bit confusing is Open Mesh Effect naming itself. **"OFX"** refers to the original OpenFX spec, but it can also refer to this project, as in **"OFX mesh effect"**. The existing plugins are called **"Mfx___"**; perhaps using **"MFX"** more pervasively to refer to **"OFX mesh effect" / "Open Mesh Effect"** would be better branding? It's not direct abbreviation, but **"OME"** looks silly to me :)

**Comment by eliemichel** [comment]
Good call for adding the image to the C doc as well, I just did it. :)

Yes, Blender confuses vertices and loops because I think they designed the notion of "loop" only as an internal name at first and did not want to expose it to the user (because it means nothing). That's why I think we should get away from this term, it has been used too much to mean different things. I don't like "element" neither, whereas "corner" really mean what it is.

Do you mean replacing `OfxMeshEffect` with `Mfx` in all constant names? Or "OpenMfx"? Indeed I've come up with using "MFX" when abbreviating because idk why but I don't like "OME", but then it makes the mapping MFX (short name) <-> OpenMeshEffect (long name) unclear at first glance. BTW I also use with myself the convention that `MfxFoo` designates a plugin and `FooMfx` a host.

**Comment by tkarabela** [comment]
OpenFX uses `OfxImageEffect` to refer to image-specific parts of the API, so `OfxMeshEffect` feels just right in the API names. I was thinking more in terms of how to refer to the project in general, without using the full name. **OpenMfx** (or **OpenMFX**) didn't come to my mind - it looks nice! And it suggests relation to OpenFX better than **MFX** does; also "Open Mesh Effect" <-> "OpenMFX" doesn't seem as surprising as just "MFX".

Regarding vertices vs. corners, it's your call - both work for me :)

**Comment by eliemichel** [comment]
Little heads up: I am planning on doing this renaming of "vertex" into "corner" and "Open Mesh Effect" into "OpenMfx" soon!

**Comment by eliemichel** [comment]
The (breaking) renaming is available for preview in the `rename` branch: https://github.com/eliemichel/OpenMeshEffect/tree/rename

**Comment by eliemichel** [comment]
Renaming is ready to be merged, awaiting for plugins to migrate (MfxVCG ok, MfxVTK PRed).

**Comment by tkarabela** [comment]
Thanks for the pull request, MfxVTK should be ready as well. I think the latest release of MfxVTK is a bit behind master, I should make a new release. If you're going to implement the renaming into the new Blender 2.93 host, I think I'll wait for that and then test everything to make sure it works, update docs and make a new release.

BTW, glad to see Mfx moving again! :)

**Comment by eliemichel** [comment]
Here we are, thanks for merging my PR on MfxVTK, now MfxVCG switched to the renamed version as well as this repo and OpenMfxForBlender. The last release is based on 2.93 LTS. I have also updated the whole documentation.

@tkarabela happy to see you're still interested! I just sent you an email btw.
